# Generated by Django 3.2 on 2024-02-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240214_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='confirmation_code',
        ),
    ]
