# Generated by Django 3.2 on 2024-02-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_myuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default=1, max_length=150, unique=True, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
