# Generated by Django 3.2 on 2024-02-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True, default=1, verbose_name='Биография пользователя'),
            preserve_default=False,
        ),
    ]
