# Generated by Django 3.2 on 2024-02-20 18:12

import django.contrib.auth.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_myuser_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='myuser',
            name='Username me is not valid',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator, users.validators.NotEqualMeUsernameValidator], verbose_name='Имя пользователя'),
        ),
    ]
